version: '3.8'

services:
  server:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/app
    command: npm start
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/auth
      REDIS_URI: redis://redis:6379

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/auth
      POSTGRES_DB: auth
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
